name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 unzip zlib1g-dev libffi-dev libssl-dev autoconf automake libtool curl make libncurses-dev libncursesw5-dev cmake
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Download Xray Binary
        run: |
          curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/download/v1.8.4/Xray-android-arm64-v8a.zip
          unzip xray.zip xray
          chmod +x xray

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EVEVPN-package
          path: bin/*.apk
